#!/usr/bin/env python

import sys

from rqt_gui.main import Main
from rqt_plotxy.plotxy import PlotXY

plugin = 'rqt_plotxy.plotxy.PlotXY'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin,
                   plugin_argument_provider=PlotXY.add_arguments))
