#!/usr/bin/env python

import sys

from rqt_gui.main import Main
from rqt_shell.shell import Shell

plugin = 'rqt_shell.shell.Shell'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin, plugin_argument_provider=Shell.add_arguments))
